# Generated by Django 4.2.26 on 2025-11-25 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_alter_recommendation_options_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['student', 'date'], name='activities_student_24e834_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['student', 'timestamp'], name='activities_student_0ea652_idx'),
        ),
        migrations.AddIndex(
            model_name='progress',
            index=models.Index(fields=['student', 'status'], name='progress_student_1b8978_idx'),
        ),
        migrations.AddIndex(
            model_name='progress',
            index=models.Index(fields=['lesson', 'status'], name='progress_lesson__b32da4_idx'),
        ),
        migrations.AddIndex(
            model_name='progress',
            index=models.Index(fields=['student', '-last_accessed'], name='progress_student_8b481e_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendation',
            index=models.Index(fields=['student', 'is_dismissed'], name='report_reco_student_2ba3f9_idx'),
        ),
    ]
